name 'cesnet-hadoop_lib'
version '0.2.1'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-hadoop_lib'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'Common puppet library for Hadoop modules'
description 'Common puppet library for Hadoop modules'
project_page 'https://github.com/MetaCenterCloudPuppet/cesnet-hadoop_lib'

dependency 'puppetlabs/stdlib', '>=1.0.0 <5.0.0'
dependency 'adrien/alternatives', '>=0.3.0 <1.0.0'
