# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#   Search the array and returns the index.
#
Puppet::Functions.create_function(:'hadoop_lib::array_search') do
  # @param arguments
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :arguments
  end


  def default_impl(*arguments)
    

    raise(Puppet::ParseError, "array_search(): Wrong number of arguments") if arguments.size != 2

    raise(Puppet::ParseError, "array_search(): Not an array") if !arguments[0].is_a?(Array)

    array = arguments[0]
    value = arguments[1]

    i = array.find_index(value)
    i ? i + 1 : 0
  
  end
end
